### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by rdebeasi** [d521bb85/react-use-rect#494]
Now that [React 19 RC is out](https://react.dev/blog/2024/04/25/react-19), would you consider adding support for React 19?

I think the work here would be to test the package with React 19 RC and then update the version range in peer dependencies to something like:

```json
"peerDependencies": {
  "react": "^17.0.2 || ^18.0.0 || ^19.0.0 || ^19.0.0-rc"
},
```

I'd be happy to lend a hand testing. If that would be useful, just let me know. Thank you!

**Comment by d521bb85** [comment]
HI @rdebeasi,

Thank you for the contribution! I've just merged your PR and published a new version.
